os: osx
osx_image: xcode10.2
language: node_js
node_js: '12'
before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
before_script:
  - ./node_modules/.bin/electron-rebuild
script:
  - npm test
  - npm run dist
